spring.application.name=stockai

server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://${DATABASE_URL:localhost:5432/stockai}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

google.api.model=gemini-3.5-flash

jwt.secret=${JWT_SECRET}

# Railway redeploy